# Generated by Django 5.1.1 on 2024-10-05 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_user_delete_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
