# Generated by Django 5.1.1 on 2024-10-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
