# Generated by Django 5.1.1 on 2024-10-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_user_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('ngo_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ngo_name', models.CharField(max_length=100)),
                ('ngo_email', models.CharField(max_length=100)),
                ('phone1', models.BigIntegerField(blank=True, null=True)),
                ('phone2', models.BigIntegerField(blank=True, null=True)),
                ('building_house_no', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'ngo',
                'managed': False,
            },
        ),
    ]
