# Generated by Django 5.1.1 on 2024-10-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_ngo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.IntegerField(default=0)),
                ('shoes', models.IntegerField(default=0)),
                ('stationary', models.IntegerField(default=0)),
                ('clothes', models.IntegerField(default=0)),
                ('food', models.IntegerField(default=0)),
                ('toys', models.IntegerField(default=0)),
                ('fname', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('pin', models.CharField(max_length=10, null=True)),
                ('donation_date', models.DateField(null=True)),
            ],
            options={
                'db_table': 'donor',
                'managed': False,
            },
        ),
    ]
