# Generated by Django 5.1.1 on 2024-10-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_donor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={},
        ),
    ]
