# Generated by Django 5.1.1 on 2024-10-05 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_donor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='donor',
            name='donor_id',
            field=models.ForeignKey(default='USER001', on_delete=django.db.models.deletion.CASCADE, to='home.user'),
        ),
    ]
