# Generated by Django 5.0.7 on 2024-10-06 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_donor_options_donor_donor_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donor',
        ),
    ]
