# Generated by Django 5.1.1 on 2024-10-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_delete_donor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('donor_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('donor_name', models.CharField(max_length=255)),
            ],
        ),
    ]
