# Generated by Django 5.1.1 on 2024-10-06 05:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_donor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books', models.IntegerField(default=0)),
                ('shoes', models.IntegerField(default=0)),
                ('stationary', models.IntegerField(default=0)),
                ('clothes', models.IntegerField(default=0)),
                ('food', models.IntegerField(default=0)),
                ('toys', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('pin', models.IntegerField(blank=True, null=True)),
                ('pick_up', models.DateField(blank=True, null=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
