# Generated by Django 5.1.1 on 2024-10-06 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_donorinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorinfo',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donor_info', to='home.user'),
        ),
    ]
