# Generated by Django 5.1.1 on 2024-10-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_deliverypartner_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeliveryPartner',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
