# Generated by Django 5.1.1 on 2024-10-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_delete_deliverypartner_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('voucher_id', models.AutoField(primary_key=True, serialize=False)),
                ('voucher_name', models.CharField(max_length=255)),
                ('discount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('T_and_C', models.TextField(blank=True, null=True)),
                ('expiry_date', models.DateField()),
                ('points_needed', models.IntegerField()),
            ],
        ),
    ]
